export * from './JobDetailCard/index';
// import 'antd/dist/antd.css';
import 'antd/dist/reset.css';
export * from './radioButtonGroup';
export * from './SideMenu';
export * from './CustomNBButton';
export * from './Icons';
export * from './CustomButton';
export * from './SelectableRadioButton';
export * from './FeatureCard';
export * from './SelectableRadioButton';
export * from './FaqCard';
export * from './StatusTag';
export * from './CandidateAvatars';
export * from './UnojobsIcons';
export * from './LeftSideScreen';
export * from './Authentication';
export * from './SuperAdmin';
export * from './EmployerDashboard';
export * from './TopMatches';
export * from './VideoCallPlatform';
export * from './NotificationAlert';
export * from './UnoAlertNotification';
export * from './LandingBadge';
export * from './CurvedUnderlineText';
export * from './CommonScreen';
