export const style = {
  input: {
    width: '400px',
    height: '45px',
    borderRadius: '5px',
    padding: '12px 20px',
    fontSize: '14px',
    color: '#111111',
    letterSpacing: '0.03em',
  },
  submitButton: {
    width: '400px',
    backgroundColor: '#4169E0',
  },
  heading: {
    width: '400px',
    fontSize: '36px',
    color: '#111111',
    fontWeight: 600,
    display: 'block',
    marginTop: '15px',
  },
  subHeading: {
    width: '400px',
    fontSize: '16px',
    color: '#111111',
    fontWeight: 400,
    display: 'block',
    marginTop: '10px',
    marginBottom: '50px',
  },
  userType: {
    marginBottom: '78px',
    marginTop: '10px',
  },
  forgetText: {
    maxWidth: '400px',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: '30px',
    marginBottom: '30px',
    cursor: 'pointer',
    color: '#4169E0',
  },
  registerText: {
    color: '#4169E0',
    cursor: 'pointer',
  },
  commonText: {
    fontSize: '14px',
    fontWeight: 400,
  },
  iconButton: {
    variant: 'outline',
    height: '48px',
    width: '50px',
    padding: '8px',
    borderWidth: '1.5px',
    borderColor: '#EBF4FF',
    borderStyle: 'solid',
    backgroundColor: '#FFFFFF',
  },
  smButtons: {
    width: '400px',
    space: '16px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainContainer: {
    width: '400px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    space: '30px',
  },
  backArrowIcon: {
    width: '0px',
    height: '0px',
    fontSize: '50px',
    cursor: 'pointer',
    marginRight: 'auto',
    marginTop: '30px',
  },
};
