export const style = {
  input: {
    width: 400,
    height: 45,
    borderRadius: 5,
    padding: '12px 20px',
    fontSize: 14,
    color: '#111111',
    letterSpacing: '0.03em',
  },
  submitButton: {
    width: '400px',
    backgroundColor: '#4169E0',
  },
  heading: {
    width: 400,
    fontSize: 36,
    color: '#111111',
    fontWeight: 600,
    display: 'block',
    marginTop: 15,
  },
  subHeading: {
    width: 400,
    fontSize: 16,
    color: '#111111',
    fontWeight: 400,
    display: 'block',
    marginTop: 10,
    marginBottom: 50,
  },
  userType: {
    marginBottom: 78,
    marginTop: 10,
  },
  forgetText: {
    maxWidth: 400,
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 30,
    cursor: 'pointer',
    color: '#4169E0',
  },
  registerText: {
    color: '#4169E0',
    cursor: 'pointer',
  },
  commonText: {
    fontSize: 14,
    fontWeight: 400,
  },
  iconButton: {
    variant: 'outline',
    height: 12,
    width: 50,
    padding: 2,
    borderWidth: 1.5,
    borderColor: '#EBF4FF',
    borderStyle: 'solid',
    backgroundColor: '#FFFFFF',
  },
  smButtonsContainer: {
    width: 400,
    space: 8,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainContainer: {
    width: 400,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    space: 30,
  },
  backIconButton: {
    width: 0,
    height: 0,
    fontSize: 50,
    cursor: 'pointer',
    marginRight: 'auto',
  },
  backArrowIcon: {
    marginTop: 30,
  },
  backArrowModalIcon: {
    marginTop: 15,
    marginLeft: 15,
  },
  modalPosition: {
    maxWidth: 430,
    backgroundColor: '#FFFFFF',
    maxHeight: 'auto',
    position: 'absolute',
    left: '50%',
    top: '50%',
    marginTop: 'auto',
    marginLeft: -215,
    marginRight: 0,
    marginBottom: 0,
  },
  otpInputStyle: {
    width: 60,
    height: 40,
    border: '1px solid #F3F3F3',
    borderRadius: 5,
  },
  otpErrorInput: {
    border: '1px solid red',
  },
  otpSeperatorStyle: {
    width: 8,
  },
};
